# Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# SPDX-License-Identifier: MPL-2.0

# labels to be used with /area command
area:
  - 'tflint'
  - 'github'

kind:
  - 'bug'
  - 'documentation'
  - 'discussion'
  - 'feature'
  - 'question'
  - 'support'

priority:
  - backlog
  - 'low'
  - 'medium'
  - 'high'
  - 'critical'

status:
  - available
  - blocked
  - in_progress
  - on_hold

# File globs for PR labeler
# tests:
#   - '**/*.test.ts'

'area/github':
  - .github/*
  - .github/**/*

'area/tflint':
  - rules/*

'kind/documentation':
  - README.md
