# Copyright (C) 2021 Nicolas Lamirault <nicolas.lamirault@gmail.com>
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
        args:
        - '--allow-multiple-documents'
        exclude: mkdocs.yml
    -   id: check-added-large-files
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.10
    hooks:
    -   id: insert-license
        files: \.go
        args:
        - --license-filepath
        - hack/config/license.txt
        - --comment-style
        - //
    -   id: insert-license
        files: Makefile
        args:
        - --license-filepath
        - hack/config/license.txt
- repo: git://github.com/dnephin/pre-commit-golang
  rev: master
  hooks:
    - id: go-fmt
    - id: go-vet
    # - id: go-lint
    # - id: go-imports
    # - id: go-cyclo
    #   args: [-over=15]
    - id: validate-toml
    - id: no-go-testing
    # - id: golangci-lint
    # - id: go-critic
    - id: go-unit-tests
    - id: go-build
    - id: go-mod-tidy
