# Copyright (C) 2021 Nicolas Lamirault <nicolas.lamirault@gmail.com>
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

name: Project / Draft PR Labels

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - name: label swapping
      uses: jinmayamashita/ready-for-review@1.0.0
      with:
        in-progress-label: 'status/in_progress'
        ready-for-review-label: 'status/review_needed'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
