# Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# SPDX-License-Identifier: MPL-2.0

# name: "Label PRs from globs"
# on:
#   schedule:
#   - cron: "0 * * * *"

# jobs:
#   execute:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: jpmcb/prow-github-actions@v1.1.1
#         with:
#           jobs: 'pr-labeler'
#           github-token: "${{ secrets.GITHUB_TOKEN }}"

name: Prow / Pull Request Labeler

on:
- pull_request_target

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4.0.2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
