# Copyright (C) 2021 Nicolas Lamirault <nicolas.lamirault@gmail.com>
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

name: Renovate / Helm releases

on:
  workflow_dispatch:
  schedule:
  - cron: "0 * * * *"

jobs:
  renovate-helmrelease:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1

    # - name: Update Helm Releases
    #   run: |
    #     docker-compose run -T --rm builder bootstrap/renovate-helm-releases.sh

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: update/pre-commit-auto-update
        delete-branch: true
        title: Auto-update pre-commit hooks
        signoff: true
        committer: "Nicolas Lamirault <nlamirault@users.noreply.github.com>"
        author: "Nicolas Lamirault <nlamirault@users.noreply.github.com>"
        commit-message: Auto-update pre-commit hooks
        body: |
          Signed-off-by: Nicolas Lamirault <nlamirault@users.noreply.github.com>
        labels: dependencies, merge
